<p class="task-text <?= $block->hasCssClass() ? ' ' . $block->getCssClass() : '' ?>">This is a paragraph.</p>


<?php 
$cols = 9;
$rows = 9;

echo "<table class='multiplication_table'>";
    for ($tr = 1; $tr <= $rows; $tr ++) {
        if ($tr % 2 == 0) {
            echo "<tr class='cross'>";
        } else {
            echo "<tr>";
        }
            for ($td = 1; $td <= $cols; $td ++) {
                if ($td % 2 == 0) {
                    echo "<td class='cross'>" . $tr * $td . "</td>";
                } else {
                    echo "<td>" . $tr * $td . "</td>";
                }
            }
        echo "</tr>";
    }
echo " </table> ";
?>




<table class='multiplication_table'>

<?php 
$cols = 9;
$rows = 9;

 for ($tr = 1; $tr <= $rows; $tr ++) {
            echo "<tr>";
            for ($td = 1; $td <= $cols; $td ++) {
                if ($tr % 2 == 0 && $td % 2 == 0) {
                    echo "<td class='table_cell'>" . $tr * $td . "</td>";
                } else {
                    echo "<td>" . $tr * $td . "</td>";
                }
            }
        echo "</tr>";
    } ?>
</table>

